<a href="https://colab.research.google.com/github/jvitordeoliveira96/UFRJ_courses/blob/main/Introducao_ao_Colab_pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Autor: João Vitor de Oliveira Silva**

**Data: 16/07/2021**



---



**Adaptado de [learning-python3.ipynb]: https://gist.githubusercontent.com/kenjyco/69eeb503125035f21a9d/raw/learning-python3.ipynb**


## *Notas sobre o Colab*

Ao editar uma célula no Colab, é necessário executar novamente a célula pressionando **`<Shift> + <Enter>`**. Isso permitirá que as alterações feitas estejam disponíveis para outras células.

Use **`<Enter>`** para pular linhas na sua célula atual.

#### *Células de código*

Células que contém código fonte em Python 3. 

#### *Células de Markdown* 

Células que contém texto.

<hr>

## Referências

- https://towardsdatascience.com/getting-started-with-google-colab-f2fff97f594c?gi=e8fe3378db80
- https://try.jupyter.org
- https://docs.python.org/3/tutorial/index.html
- https://docs.python.org/3/tutorial/introduction.html
- https://daringfireball.net/projects/markdown/syntax
- https://docs.scipy.org/doc/scipy/reference/
- https://numpy.org/doc/1.21/


<hr>

## Objetos, tipos básicos e variáveis

Tudo em Python é um **objeto** e todo objeto em Python tem um **type**. Alguns tipos básicos são:

- **`int`** (integer; números inteiros)
  - `10`
  - `-3`
- **`float`** (float; números reais)
  - `7.41`
  - `-0.006`
- **`complex`** (complex; números complexos)
  - `7.41j`
  - `-0.006 + 2j`  
- **`str`** (string; uma sequência de caracteres)
  - `'this is a string using single quotes'`
  - `"this is a string using double quotes"`
  - `'''this is a triple quoted string using single quotes'''`
  - `"""this is a triple quoted string using double quotes"""`
- **`bool`** (boolean; um valor binário que é verdadeiro *True* ou falso *False*)
  - `True`
  - `False`
- **`NoneType`** (um tipo especial representando a ausência de valor. Análogo ao NULL de outras linguagens.)
  - `None`

Em Python, nome de variáves deve começar com uma letra. É possível ser usado letras maiúsculas, minúsculas, underscore (_), números...

<hr>

## Operadores básicos

No Python, existem diferentes tipos de **operadores** (símbolos especiais) que operam com valores diferentes. Alguns dos operadores básicos incluem:

- operadores aritméticos
  - **`+`** (adição)
  - **`-`** (subtração)
  - **`*`** (multiplicação)
  - **`/`** (divisão)
  - __`**`__ (potenciação)
- operadores de atribuição
  - **`=`** (atribuição a algum valor)
  - **`+=`** (adicionar e re-atribuir; incremento)
  - **`-=`** (subtrair e re-atribuir; decremento)
  - **`*=`** (multiplicação e re-atribuir)
- operadores de comparação (retornam `True` ou `False`)
  - **`==`** (igual)
  - **`!=`** (diferente)
  - **`<`**  (menor que)
  - **`<=`** (menor ou igual que)
  - **`>`**  (maior que)
  - **`>=`** (maior ou igual que)

Quando vários operadores são usados ​​em uma única expressão, ** precedência do operador ** determina quais partes da expressão são avaliadas em que ordem. Os operadores com maior precedência são avaliados primeiro (como em matemática). Operadores com a mesma precedência são avaliados da esquerda para a direita.

- `()` parenteses
- `**` potenciação
- `*`, `/` multiplicação e divisão
- `+`, `-` adição e subtração
- `==`, `!=`, `<`, `<=`, `>`, `>=` comparação

> Ver https://docs.python.org/3/reference/expressions.html#operator-precedence para mais detalhes.

In [ ]:
# Atribuindo alguns números a diferentes variáveis
num1 = 10
num2 = -3
num3 = 7.41
num4 = -.6
num5 = 7
num6 = 3
num7 = 11.11
num8 = 5 + 30j  # exemplo de número complexo

In [ ]:
# Adição
num1 + num2

7

In [ ]:
# Subtração
num2 - num3

-10.41

In [ ]:
# Multiplicação
num3 * num4

-4.446

In [ ]:
# Divisão
num4 / num5

-0.08571428571428572

In [ ]:
# Potenciação
num5 ** num6

343

In [ ]:
# Adição (complexo)
num8 + num6

(8+30j)

In [ ]:
# Potenciação (complexo)
num8**2

(-875+300j)

In [ ]:
# Incrementando uma variável existente
num7 += 4
num7

15.11

In [ ]:
# Atribua o valor de uma expressão a uma variável
num8 = num1 + num2 * num3
num8

-12.23

In [ ]:
# Essas duas expressões são iguais uma à outra?
num1 + num2 == num5

True

In [ ]:
# Essas duas expressões não são iguais uma à outra?
num3 != num4

True

In [ ]:
# A primeira expressão é menor que a segunda expressão?
num5 < num6

False

In [ ]:
# Esta expressão é True?
5 > 3 > 1

True

In [ ]:
# Esta expressão é True?
5 > 3 < 4 == 3 + 1

True

In [ ]:
# Atribua algumas strings a diferentes variáveis
simple_string1 = 'an example'
simple_string2 = "oranges "

In [ ]:
# Adição
simple_string1 + ' of using the + operator'

'an example of using the + operator'

In [ ]:
# Observe que a sequência não foi modificada
simple_string1

'an example'

In [ ]:
# Comparação entre strings
simple_string1==simple_string2

False

<hr>

## Listas, tuplas e dicionários

- **`list`** (list: mutável; indexado por inteiros; itens são armazenados na ordem em que são adicionados)
  - `[3, 5, 6, 3, 'dog', 'cat', False]`
- **`tuple`** (tuple: imutável; indexado por inteiros; itens são armazenados na ordem definida)
  - `(3, 5, 6, 3, 'dog', 'cat', False)`
- **`dict`** (dictionary: mutável; pares chave-valor são indexados pelas chaves; itens NÃO são armazenados na ordem em que são adicionados)
  - `{'name': 'Jane', 'age': 23, 'fav_foods': ['pizza', 'fruit', 'fish']}`

Ao definir listas e tuplas, use (,) para separar os itens individuais. Ao definir dicionários, use dois pontos (:) para separar chaves de valores e vírgulas (,) para separar os pares de chave e valor.


In [ ]:
list1 = [3, 5, 6, 3, 'dog', 'cat', False]
tuple1 = (3, 5, 6, 3, 'dog', 'cat', False)
dict1 = {'name': 'Jane', 'age': 23, 'fav_foods': ['pizza', 'fruit', 'fish']}

In [ ]:
# Os itens em listas são armazenados na ordem em que foram adicionados
list1

[3, 5, 6, 3, 'dog', 'cat', False]

In [ ]:
# Os itens em tuplas são armazenados na ordem em que foram adicionados
tuple1

(3, 5, 6, 3, 'dog', 'cat', False)

In [ ]:
# Os itens em dicionários NÃO são armazenados na ordem em que foram adicionados
dict1

{'age': 23, 'fav_foods': ['pizza', 'fruit', 'fish'], 'name': 'Jane'}

<hr>

## Acessando elementos de strings, listas, tuplas e dicionários.

Para strings, listas, tuplas e dict, podemos usar colchetes para acessar dados em um índice.

- strings, listas e tuplas são indexadas por números inteiros, ** começando em 0 ** para o primeiro item
  - esses tipos de sequência também oferecem suporte a vários itens, conhecidos como ** slicing **
  - use ** indexação negativa ** para iniciar na parte de final da sequência
- dicts são indexados por suas chaves.


In [ ]:
# Acesse o primeiro item em uma sequência
list1[0]

3

In [ ]:
# Acesse o primeiro item em uma sequência
tuple1[-1]

False

In [ ]:
# Acesse um intervalo de itens em uma sequência
simple_string1[3:8]

'examp'

In [ ]:
# Acesse um intervalo de itens em uma sequência
tuple1[:-3]

(3, 5, 6, 3)

In [ ]:
# Acesse um intervalo de itens em uma sequência
list1[4:]

['dog', 'cat', False]

In [ ]:
# Accesse um item em um dicionário
dict1['name']

'Jane'

In [ ]:
# Acesse um elemento de uma sequência em um dicionário
dict1['fav_foods'][2]

'fish'

In [ ]:
# Acessar um elemento inexistente gera erros
list1[8]

IndexError: ignored

In [ ]:
dict1['address']

## Alguns métodos de listas

- **`.append(item)`** adiciona um novo elemento item ao final da lista
- **`.extend([item1, item2, ...])`** adiciona todos os elementos de uma outra lista ao final da lista
- **`.remove(item)`** remove o elemento *item* da lista (se existir)
- **`.pop()`** remove e retorna o ultimo element da lista
- **`.pop(index)`** remove e retorna o elemento de indíce *index*

In [ ]:
list_t = []

In [ ]:
list_t.append(2.4)
list_t

[2.4]

In [ ]:
list_t.extend([2.75, 2.2])
list_t

[2.4, 2.75, 2.2]

In [ ]:
# Se for usado append, será adicionado uma lista para a lista
# ao invés de apenas o elemento
list_t.append([2.75, 2.2])
list_t

[2.4, 2.75, 2.2, [2.75, 2.2]]

In [ ]:
list_t.remove(2.75)
list_t

[2.4, 2.2, [2.75, 2.2]]

In [ ]:
list_t2 = list_t.pop()
list_t, list_t2

([2.4, 2.2], [2.75, 2.2])

## Alguns métodos de dicionários

- **`.update([(key1, val1), (key2, val2), ...])`** adiciona diversos pares chave/valor ao dicionário
- **`.update(dict2)`** adiciona todos os pares chave/valor ao dicionário
- **`.pop(key)`** remove a chave *key* e retorna o seu valor do dicionário (erro se não existir)
- **`.pop(key, default_val)`** remove a chave *key* e retorna o seu valor do dicionário (ou retorna default_val se a chave não for encontrada, evitando o erro anterior)
- **`.keys()`** retorna uma lista com todas as chaves do dicionário
- **`.values()`** retorna uma lista com todos os valores do dicionário
- **`.items()`** retorna uma view com todos os pares chave/valor do dicionario

In [ ]:
my_data = {"name": "Joao", "age": 23, "institution": "LNCC"}

In [ ]:
my_data.update([('occupation', 'graduate student')])

In [ ]:
my_data

{'age': 23,
 'institution': 'LNCC',
 'name': 'Joao',
 'occupation': 'graduate student'}

In [ ]:
s = my_data.pop('age')
s

23

In [ ]:
# Apos removido, ocorre um erro ao acessar esta chave
my_data['age']

KeyError: ignored

<hr>

## Funções internas

Uma **função** é um objeto Python que você pode "chamar" para **executar uma ação** ou calcular e **retornar outro objeto**. Você chama uma função colocando parênteses à direita do nome da função. Algumas funções permitem passar **argumentos** entre parênteses (separando vários argumentos com vírgula). Internos à função, esses argumentos são tratados como variáveis.

O Python possui várias funções internas úteis para ajudá-lo a trabalhar com diferentes objetos e / ou seu ambiente. Aqui está uma pequena amostra deles:

- **`type(obj)`** para determinar o tipo de um objeto
- **`len(container)`** para determinar quantos itens estão em um container
- **`input(opt_str)`** ler um input do teclado, podendo ter uma mensagem opcional

> Lista completa de funções internas: https://docs.python.org/3/library/functions.html


In [ ]:
# Use a função type() para determinar o tipo de um objeto
type(simple_string1)

str

In [ ]:
# Use a função len() para determinar quantos itens estão em um container
len(dict1)

3

In [ ]:
# Use a função len() para determinar quantos itens estão em um container
len(simple_string2)

8

In [ ]:
string1 = input("Digite uma sequência de caracteres:")

Digite uma sequência de caracteres:Le


In [ ]:
string1

'Le'

<hr>

## Casting de tipos
O ato de fazer **casting** é o de converter uma expressão de um tipo para outro. Alguns exemplos 

- **`str(expr)`** converte expr em string
- **`int(expr)`** converte expr em int
- **`float(expr)`** converte expr em float



In [ ]:
str(5.256)

'5.256'

In [ ]:
string3 = "3.14"
float(string3)

3.14

In [ ]:
int(5.561)

5

In [ ]:
# float e int são incapazes de converter listas
# seria necessário fazer a conversão elemento a elemento
float([1, 3, 4, 5])

TypeError: ignored

In [ ]:
list_t3 = [1, 3, 4, 5]
list_t3[0] = float(list_t3[0])
list_t3

[1.0, 3, 4, 5]

## Python "for loops"

É fácil **iterar** sobre uma coleção de itens usando um **loop `for`**. As strings, listas, tuplas e dicionários que definimos são todos objetos **iteráveis​**.

O loop for percorrerá o objeto especificado, um item de cada vez, e fornecerá uma variável temporária para o item atual. Você pode usar essa variável temporária como uma variável normal.

No caso de listas, é possível realizar o acesso indíce a indíce como o comando **`range`**

In [ ]:
my_list5 = ['abacaxi', 'maçã', 'pêssego', 387.525, 'limão']
dict1 = {'name': 'Jane', 'age': 23, 'fav_foods': ['pizza', 'fruit', 'fish']}

In [ ]:
# acesso elemento a elemento sem índice
for element in my_list5:
  print(element)

abacaxi
maçã
pêssego
387.525
limão


In [ ]:
# acesso elemento a elemento com índice
for j in range( 0, len(my_list5) ):
  print(my_list5[j])

abacaxi
maçã
pêssego
387.525
limão


In [ ]:
for key, value in dict1.items():
  print(str(key) + ": " + str(value))

name: Jane
age: 23
fav_foods: ['pizza', 'fruit', 'fish']


## Python "if" e "loops while"

O comando **`if`** permite que se teste uma condição e realiza uma série de outros comandos se esta for **True**. É possível usar dos comandos else e elif se for necessário tomar ações adicionais no caso desta condição avaliar **False**.

O loop **`while`** vai continuar a repetir uma sequência de comandos até que a condição passe a ser avaliada como **False**.

> OBS$_1$: É possível que um loop **`while`** execute indefinidamente se a condição avaliada nunca passa a ser **False**


In [ ]:
# Exemplo usando if, elif e else
num = 1122
if (9 < num < 99):
    print("Two digit number")
elif (99 < num < 999):
    print("Three digit number")
elif (999 < num < 9999):
    print("Four digit number")
else:
    print("number is <= 9 or >= 9999")

Four digit number


In [ ]:
num2 = 10
while(num2>0):
  print(num2, end = ' ')
  num2 += -1

10 9 8 7 6 5 4 3 2 1 

## Definindo funções

A definição de uma função em Python pode ser feita da seguinte forma:

```python
def function_name(arg1, arg2, ..., opt_arg1 = value1, opt_arg2 = value2, ...):
  # Lógica da função


  return return1, return2, ...
```

- **`function_name`**: nome da função desejada
- **`arg1`**: nome do primeiro argumento obrigatório
- **`arg2`**: nome do segundo argumento obrigatório
- **`opt_arg1`**: nome do primeiro argumento opcional. Se não for especificado, o valor será o valor padrão value1
- **`opt_arg2`**: nome do primeiro argumento opcional. Se não for especificado, o valor será o valor padrão value2
- **`return1`**, **`return2`** são saídas retornadas ao fim da execução da função

Vejamos alguns exemplos:


In [ ]:
def parabola(x, a = 1, b = 0, c = 0):
  return a * x**2 + b * x + c

In [ ]:
parabola(2) # Usando apenas o argumento obrigatório, estaremos
            # tratando da parábola y = 1 * x**2

4

In [ ]:
parabola(2, a = 1, b = 1)  # Agora, tratando da parábola com a = 1, b = 1

6

In [ ]:
parabola(2, a = 1, b = 1, c = 1)

7

In [ ]:
# Exemplo de função com múltiplos retornos
def area_volume_cubo(lado):
  return 6 * lado**2, lado**3

In [ ]:
resp = area_volume_cubo(4)
resp

(96, 64)

In [ ]:
# É possível atribuir retornos multiplos em um mesmo número variáveis distintas 
area_c, volume_c = area_volume_cubo(4)

In [ ]:
area_c

96

In [ ]:
volume_c

64

## Importando módulos

Existem diversos módulos disponíveis para a linguagem Python, muitas delas fundamentais para solução de problemas. A importação pode ser feita das seguintes formas:

- **`import bibnome`**: Desta forma, toda as funcionalidades da biblioteca será realizadas com `bibnome.funcao(...)` 
- **`import bibnome as bib`**: Funciona da mesma maneira, mas usando o alias 
 `bib.funcao(...)` 
- **`from bibnome import funcao`**: importa apenas `funcao` da biblioteca `bibnome`. Para utilizá-la, basta fazer `funcao(...)` 



## Importando Numpy e Scipy

O numpy e o scipy são bibliotecas que possuem uma série de funções e estruturas que permitem realização de cálculos científicos envolvendo matrizes e vetores, além de diversos métodos numéricos. A estrutura básica usada nos métodos é o Numpy array. A documentação de ambas as bibliotecas pode ser acessada em https://docs.scipy.org/doc/

De início, vamos importar ambas as bibliotecas da seguinte forma:

```python
import numpy as np
import scipy as sp
```
O uso dos alias **`np`** e **`sp`** são opcionais, mas é muito comum serem usados pela comunidade. 



In [ ]:
import numpy as np
import scipy as sp
import scipy.linalg  # necessario para certas funcoes de Alg Lin Computacional

## Numpy arrays

In [ ]:
# Exemplo de criação de vetores de duas entradas (com entradas float)
v = np.array([1., 2.])

In [ ]:
v

array([1., 2.])

In [ ]:
# Exemplo de criação de uma matriz 2x2 (com entradas float)
A = np.array(
    [[2, -0.5],[-0.5, 2]]
)

In [ ]:
A

array([[ 2. , -0.5],
       [-0.5,  2. ]])

Além de criar Numpy arrays informando uma lista, existem funções da próprio biblioteca para criá-los. Algumas delas são:

- **`zeros( (dim1, dim2,...) )`**: cria um Numpy array de dimensão da tupla (dim1, dim2, ...) com 0's em todas as entradas.
- **`ones(dim)`**: cria um Numpy array de dimensão da tupla (dim1, dim2, ...) com 1's todas as entradas.
- **`eye(dim)`**: cria um Numpy array sendo uma matriz identidade de dimensão dim x dim.
- **`linspace(a, b, npts)`**: cria um Numpy array (1D, vetor) onde cada entrada são **npts** pontos igualmente espaçados entre **a** e **b**. Muito usado para gerar *grids*.


- **`random.rand(dim1, dim2, ...)`**: cria um Numpy array aleatório (distribuição uniforme no intervalo [0, 1]) com dimensões dim1 x dim2 x ...


In [ ]:
z = np.zeros((2,2))

In [ ]:
z

array([[0., 0.],
       [0., 0.]])

In [ ]:
Idt = np.eye(2)

In [ ]:
Idt

array([[1., 0.],
       [0., 1.]])

In [ ]:
w = np.random.rand(2)

In [ ]:
w

array([0.22397968, 0.0009587 ])

In [ ]:
xg = np.linspace(-1, 1, 8)

In [ ]:
xg

array([-1.        , -0.71428571, -0.42857143, -0.14285714,  0.14285714,
        0.42857143,  0.71428571,  1.        ])

Numpy arrays possuem **operadores** definidos, que podem ser operados entre  2
Numpy arrays ou entre um Numpy array e um número

- operadores 
  - **`+`** (adição)
  - **`-`** (subtração)
  - **`*`** (multiplicação; *elementwise*)
  - **`/`** (divisão; *elementwise*)
  - __`**`__ (potenciação; *elementwise*)
  - `@` (multiplicação matricial, produto interno)

In [ ]:
# Adição/subtração
v + v

array([2., 4.])

In [ ]:
v - 3

array([-2., -1.])

In [ ]:
# Multiplicação (por escalar)
v * 2

array([2., 4.])

In [ ]:
# Multiplicação (elementwise, vetor-vetor)
v * v

array([1., 4.])

In [ ]:
# Multiplicação (elementwise, matriz-vetor)
A * v

array([[ 2. , -1. ],
       [-0.5,  4. ]])

In [ ]:
# Divisão (escalar)
1 / A

array([[ 0.5, -2. ],
       [-2. ,  0.5]])

In [ ]:
# Potenciação (elementwise, vetor)
v**2

array([1., 4.])

In [ ]:
# Potenciação (elementwise, matriz)
A**2

array([[4.  , 0.25],
       [0.25, 4.  ]])

In [ ]:
# Potenciação (elementwise, matriz)

# Atenção, isso não inverte a matriz A!
# É o mesmo que 1/A !

A**(-1)

array([[ 0.5, -2. ],
       [-2. ,  0.5]])

In [ ]:
# Multiplicacao matricial/produto interno
# (vetor - vetor) 
v @ v

5.0

In [ ]:
# Multiplicacao matricial/produto interno
# (matriz-vetor)
A @ v

array([1. , 3.5])

In [ ]:
# Multiplicao matricial
# (matriz - matriz) 
A @ A

array([[ 4.25, -2.  ],
       [-2.  ,  4.25]])

## Acesso e modificação de Numpy arrays

O acesso individual a um elemento de um Numpy array pode ser feito da mesma forma que em listas nativas da linguagem Python. Além disso, usando fateamento, somos capazes de obter trechos específicos de interesse como uma coluna ou uma linha de uma matriz.

In [ ]:
A

array([[ 2. , -0.5],
       [-0.5,  2. ]])

In [ ]:
# Acesso de um elemento de um Numpy array
A[0][1]

-0.5

In [ ]:
# Forma alternativa de acesso a um elemento de um Numpy array
A[0,1]

-0.5

In [ ]:
# Alteracao de um elemento de um Numpy array
A[0,1] = -1

In [ ]:
A

array([[ 2. , -1. ],
       [-0.5,  2. ]])

In [ ]:
# Acessando a primeira coluna de um Numpy array
A[:, 0]

array([ 2. , -0.5])

In [ ]:
# Acessando a segunda linha de um Numpy array
A[1, :]

array([-0.5,  2. ])

In [ ]:
# Alterando a segunda linha de um Numpy array para uma outra de dimensão compativel
A[1, :] = np.array([7, 10])

In [ ]:
A

array([[ 2., -1.],
       [ 7., 10.]])

Também somos capazes de obter as dimensões de um Numpy array usando o atributo **``shape``**. É retornada uma tupla com estas informações.

In [ ]:
v.shape  

(2,)

In [ ]:
A.shape

(2, 2)

In [ ]:
# Conta arbitraria: soma entre numero de linhas e colunas
A.shape[0] + A.shape[1]  

4

## Funções matemáticas e auxiliares (Numpy)

Existe uma série de funções matemáticas presentes em ambas as bibliotecas que operam sobre números (**int**, **float**, **complex**)  e Numpy arrays. Alguns exemplos:

- **`cos(np_arr)`**: calcula o cosseno *elementwise* de um Numpy array **np_arr**
- **`exp(np_arr)`**: calcula a função exponencial *elementwise* de um Numpy array **np_arr**
- **`sqrt(np_arr)`**: calcula a raiz quadrada *elementwise* de um Numpy array **np_arr**
- **`around(np_arr, decimals = d)`**: arredonda todos os elementos de um Numpy array **np_arr** até **d** (int) casas decimais (também funciona com apenas um número)
- **`clip(np_arr, low, high)`**: faz com que todos os elementos de um Numpy array **np_arr** menores que o número **low** passem a assumir este valor e números maiores que **high** passem a assumir este valor (também funciona apenas com um número)



Outras diversas funções podem ser consultadas https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [ ]:
xg

array([-1.        , -0.71428571, -0.42857143, -0.14285714,  0.14285714,
        0.42857143,  0.71428571,  1.        ])

In [ ]:
np.cos(xg)

array([0.54030231, 0.75556135, 0.90956035, 0.98981326, 0.98981326,
       0.90956035, 0.75556135, 0.54030231])

In [ ]:
# Tirar raiz quadrada de número real negativa gera um float
# nan (not a number)
np.sqrt(xg)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


array([       nan,        nan,        nan,        nan, 0.37796447,
       0.65465367, 0.84515425, 1.        ])

In [ ]:
# Convertendo todas as entradas para o tipo complex
# Casting é feito com o comando astype
xg_c = xg.astype(complex)
xg_c

array([-1.        +0.j, -0.71428571+0.j, -0.42857143+0.j, -0.14285714+0.j,
        0.14285714+0.j,  0.42857143+0.j,  0.71428571+0.j,  1.        +0.j])

In [ ]:
# Um Numpy array com entradas complexas não há este problema
np.sqrt(xg_c)

array([0.        +1.j        , 0.        +0.84515425j,
       0.        +0.65465367j, 0.        +0.37796447j,
       0.37796447+0.j        , 0.65465367+0.j        ,
       0.84515425+0.j        , 1.        +0.j        ])

In [ ]:
np.around(xg, decimals = 3)

array([-1.   , -0.714, -0.429, -0.143,  0.143,  0.429,  0.714,  1.   ])

In [ ]:
# Numpy array, entradas distribuidas uniformemente em [0,5]
xt = np.random.rand(5) * 5
xt 

array([2.17465736, 4.43901217, 2.76187391, 0.12562413, 3.89799516])

In [ ]:
np.clip(xt, 2, 4)

array([2.17465736, 4.        , 2.76187391, 2.        , 3.89799516])

## Funções matemáticas e auxiliares (Scipy.linalg)

- **`norm(np_arr)`**: calcula a norma de um Numpy array **np_arr**.
- **`det(np_arr)`**: calcula o determinante de um Numpy array **np_arr**
- **`eig(np_arr)`**: calcula os autovalores e autovetores de um Numpy array **np_arr**, retornando uma tupla em que o primeiro elemento são os autovalores e o segundo elemento os respectivos autovetores.   

Outras diversas funções podem ser consultadas https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [ ]:
r = np.array([2, -4])

In [ ]:
sp.linalg.norm(r)

4.47213595499958

In [ ]:
B = np.array([[4, 0],
              [2, -1]])

In [ ]:
sp.linalg.det(B)

-4.0

In [ ]:
sp.linalg.eig(B)

(array([-1.+0.j,  4.+0.j]), array([[0.        , 0.92847669],
        [1.        , 0.37139068]]))

## Exercícios para fixação

1) Desenvolva uma função em Python para calcular toda sequência de Fibonacci até o n-ésimo termo, armazenando todos os termos calculados em uma lista.

In [ ]:
# possível protótipo de função
def fib(n):
  """ Retorna uma lista com os n primeiros termos da sequência
  de fibonacci
  int -> list """

  # Aqui segue seu código

2) Desenvolva uma função em Python para receber dois vetores $v$ e $w$ (Numpy arrays) e retorne o cosseno do ângulo que estes formam. 

Dica: Use a relação do produto interno (algébrico e geométrico):
$$ v \cdot w = ||v|| ||w|| \cos({\theta})$$
no qual $\theta$ é o ângulo formado por estes dois vetores.

Dica2: Use que
$$||v|| = \sqrt{v \cdot v}, \quad ||w|| = \sqrt{w \cdot w}$$ 
ou use a função **``sp.linalg.norm``**.

In [ ]:
# possível protótipo de função
def cos_vet(v, w):
  """ Calcula o produto interno entre dois numpy arrays de dimensões compatíveis
  numpy array, numpy array -> float """

  # Aqui segue seu código